
insert into `item` (`upc`, `title`) values('1111','The Chronicles of Life and Death');
insert into `item` (`upc`, `title`) values('1140','Saturdays = Youth');
insert into `item` (`upc`, `title`) values('4624','Aquarium');
insert into `item` (`upc`, `title`) values('5747','What Makes You Beautiful - Single');
insert into `item` (`upc`, `title`) values('6279','Girl Gone Wild - Single');
insert into `item` (`upc`, `title`) values('6518','The Cars');
insert into `item` (`upc`, `title`) values('7485','Gavin DeGraw');
insert into `item` (`upc`, `title`) values('8408','Camp');
insert into `item` (`upc`, `title`) values('9101','Gimme Some');
insert into `item` (`upc`, `title`) values('9999','I Know You Want Me (Calle Ocho) - EP');
insert into `item` (`upc`, `title`) values('10125','Simple Plan');
insert into `item` (`upc`, `title`) values('10426','In a Tidal Wave of Mystery');
insert into `item` (`upc`, `title`) values('12729','Good Morning Revival');
insert into `item` (`upc`, `title`) values('13621','Cupid Shuffle - Single');
insert into `item` (`upc`, `title`) values('13649','Please');
insert into `item` (`upc`, `title`) values('15390','Days Go By');
insert into `item` (`upc`, `title`) values('15639','Brand New Eyes');
insert into `item` (`upc`, `title`) values('15715','The E.N.D. (The Energy Never Dies)');
insert into `item` (`upc`, `title`) values('16852','The Young & The Hopeless');
insert into `item` (`upc`, `title`) values('17525','No Superstar');
insert into `item` (`upc`, `title`) values('17665','Boombastic');
insert into `item` (`upc`, `title`) values('17937','Evolution: The Hits');
insert into `item` (`upc`, `title`) values('18619','Mr. Hurricane - Single of the Week');
insert into `item` (`upc`, `title`) values('19115','Flavors of Entanglement (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('21273','Look Sharp!');
insert into `item` (`upc`, `title`) values('21489','Debut');
insert into `item` (`upc`, `title`) values('22096','In Orbit');
insert into `item` (`upc`, `title`) values('22305','Jingle Bells/Can\'t Touch This');
insert into `item` (`upc`, `title`) values('22321','Raise Your Glass - Single');
insert into `item` (`upc`, `title`) values('22496','Before the Storm');
insert into `item` (`upc`, `title`) values('24111','Time for a Change');
insert into `item` (`upc`, `title`) values('24158','Big Bad World');
insert into `item` (`upc`, `title`) values('24213','Dreaming - Single');
insert into `item` (`upc`, `title`) values('24880','The World from the Side of the Moon (Deluxe)');
insert into `item` (`upc`, `title`) values('25365','The Black Parade');
insert into `item` (`upc`, `title`) values('25574','Believe');
insert into `item` (`upc`, `title`) values('26692','Bittersweet World');
insert into `item` (`upc`, `title`) values('27374','My Love CDS');
insert into `item` (`upc`, `title`) values('28607','Chasing A Ghost');
insert into `item` (`upc`, `title`) values('28730','All American');
insert into `item` (`upc`, `title`) values('29041','Burlesque (Original Motion Picture Soundtrack)');
insert into `item` (`upc`, `title`) values('29353','Sexy Bitch (feat. Akon) - Single');
insert into `item` (`upc`, `title`) values('29509','Love Songs');
insert into `item` (`upc`, `title`) values('30905','The Sound of San Francisco - Single');
insert into `item` (`upc`, `title`) values('31153','Alive (Remixes) - EP');
insert into `item` (`upc`, `title`) values('31254','Picture Show');
insert into `item` (`upc`, `title`) values('34831','21');
insert into `item` (`upc`, `title`) values('35117','I Am Me');
insert into `item` (`upc`, `title`) values('35564','Harmony');
insert into `item` (`upc`, `title`) values('37250','Rock Steady (Bonus Track Version)');
insert into `item` (`upc`, `title`) values('39894','September - EP');
insert into `item` (`upc`, `title`) values('42236','Dangerously In Love');
insert into `item` (`upc`, `title`) values('42938','Born This Way (The Country Road Version) - Single');
insert into `item` (`upc`, `title`) values('46172','You Make Me - Single');
insert into `item` (`upc`, `title`) values('46279','Breakaway');
insert into `item` (`upc`, `title`) values('48657','The City');
insert into `item` (`upc`, `title`) values('50146','Gildas & Jerry Kitsuné Soleil Mix');
insert into `item` (`upc`, `title`) values('50312','Recover - EP');
insert into `item` (`upc`, `title`) values('50442','Nick Jonas (Deluxe Version)');
insert into `item` (`upc`, `title`) values('50447','Shower - Single');
insert into `item` (`upc`, `title`) values('51567','Lucid Dreams - Single');
insert into `item` (`upc`, `title`) values('51662','Synchronicity');
insert into `item` (`upc`, `title`) values('51780',NULL);
insert into `item` (`upc`, `title`) values('53172','We Sing. We Dance. We Steal Things.');
insert into `item` (`upc`, `title`) values('53488','Troubadour (Champion Edition)');
insert into `item` (`upc`, `title`) values('53564','304');
insert into `item` (`upc`, `title`) values('57927','Summertime - Single');
insert into `item` (`upc`, `title`) values('60031','My Love (feat. Jess Glynne) - Single');
insert into `item` (`upc`, `title`) values('60769','The Greatest Hits - Why Try Harder');
insert into `item` (`upc`, `title`) values('62287','Abbey Road (Remastered)');
insert into `item` (`upc`, `title`) values('62841','KC and the Sunshine Band');
insert into `item` (`upc`, `title`) values('64775','Curious');
insert into `item` (`upc`, `title`) values('66076','Until I Stay (Remix Bundle) - EP');
insert into `item` (`upc`, `title`) values('68691','Blink-182: Greatest Hits');
insert into `item` (`upc`, `title`) values('68989','Ma Fleur');
insert into `item` (`upc`, `title`) values('71006','Queen Rock Montreal (Live)');
insert into `item` (`upc`, `title`) values('71211','Marry the Night (The Remixes)');
insert into `item` (`upc`, `title`) values('71572','Levels (Remixes) - EP');
insert into `item` (`upc`, `title`) values('71683','Foo Fighters: Greatest Hits');
insert into `item` (`upc`, `title`) values('72910','Win a Date With Tad Hamilton');
insert into `item` (`upc`, `title`) values('73683','You Know You Like It - Single');
insert into `item` (`upc`, `title`) values('73912','The Fame');
insert into `item` (`upc`, `title`) values('74293','Supermodel');
insert into `item` (`upc`, `title`) values('75168','Judas - Single');
insert into `item` (`upc`, `title`) values('75912','So Far So Good');
insert into `item` (`upc`, `title`) values('77121','The Sound of Revenge');
insert into `item` (`upc`, `title`) values('78028','American Idiot');
insert into `item` (`upc`, `title`) values('78319','(What\'s the Story) Morning Glory?');
insert into `item` (`upc`, `title`) values('79682','Spreading Rumours (Deluxe)');
insert into `item` (`upc`, `title`) values('79807','Real Slow - Single');
insert into `item` (`upc`, `title`) values('81621','Hits Dance Club, Vol. 31');
insert into `item` (`upc`, `title`) values('81709','Still Not Gettin\' Any');
insert into `item` (`upc`, `title`) values('82485','Life in Cartoon Motion');
insert into `item` (`upc`, `title`) values('82781','Metro Station');
insert into `item` (`upc`, `title`) values('84110','Santa Claus Lane');
insert into `item` (`upc`, `title`) values('84930','808s & Heartbreak');
insert into `item` (`upc`, `title`) values('84942','Loud');
insert into `item` (`upc`, `title`) values('85208','Incredibad (Deluxe Version)');
insert into `item` (`upc`, `title`) values('85445','Rebelution');
insert into `item` (`upc`, `title`) values('85772','Goodbye Yellow Brick Road');
insert into `item` (`upc`, `title`) values('86839','The Dutchess');
insert into `item` (`upc`, `title`) values('87578','Shwayze');
insert into `item` (`upc`, `title`) values('88755','Good News for People Who Love Bad News');
insert into `item` (`upc`, `title`) values('89096','Speak For Yourself');
insert into `item` (`upc`, `title`) values('89122','The E.N.D.');
insert into `item` (`upc`, `title`) values('89155','Now: 25 Top Hits of the 1980\'s');
insert into `item` (`upc`, `title`) values('90294','Lifehouse');
insert into `item` (`upc`, `title`) values('91052','I Bet My Life - Single');
insert into `item` (`upc`, `title`) values('91053','Satellite');
insert into `item` (`upc`, `title`) values('91787','Trash');
insert into `item` (`upc`, `title`) values('92105','Cansei de Ser Sexy');
insert into `item` (`upc`, `title`) values('92871','Million Ways - Single');
insert into `item` (`upc`, `title`) values('92926','I\'m Ready - EP');
insert into `item` (`upc`, `title`) values('93395','Work B**ch - Single');
insert into `item` (`upc`, `title`) values('93497','We Are Young (feat. Janelle Monáe) - Single');
insert into `item` (`upc`, `title`) values('93573','Spice');
insert into `item` (`upc`, `title`) values('94027','Revolver (Remastered)');
insert into `item` (`upc`, `title`) values('94437','Dreaming Out Loud');
insert into `item` (`upc`, `title`) values('94598','The High Road');
insert into `item` (`upc`, `title`) values('94698','The Best of Rick Springfield');
insert into `item` (`upc`, `title`) values('96329','I\'m A DJ - Single');
insert into `item` (`upc`, `title`) values('96427','Got Live If You Want It');
insert into `item` (`upc`, `title`) values('96565','Growing Pains');
insert into `item` (`upc`, `title`) values('97832','Crimes of Passion');
insert into `item` (`upc`, `title`) values('98084','Dance Again (feat. Pitbull) - Single');
insert into `item` (`upc`, `title`) values('98668','A Girl Like Me (Bonus Tracks)');
insert into `item` (`upc`, `title`) values('98952','Rock Steady');
insert into `item` (`upc`, `title`) values('100378','Do What U Want (feat. Marié Digby) - Single');
insert into `item` (`upc`, `title`) values('102545','Guero');
insert into `item` (`upc`, `title`) values('104780','Tetra');
insert into `item` (`upc`, `title`) values('104842','Tonight Tonight - Single');
insert into `item` (`upc`, `title`) values('104873','War & Peace');
insert into `item` (`upc`, `title`) values('105689','Figure 8 - EP');
insert into `item` (`upc`, `title`) values('106038','Torches');
insert into `item` (`upc`, `title`) values('106648','Give Me All Your Luvin\' (feat. Nicki Minaj, M.I.A.) - Single');
insert into `item` (`upc`, `title`) values('106989','Much Dance 2011');
insert into `item` (`upc`, `title`) values('107819','Tomorrow Starts Today');
insert into `item` (`upc`, `title`) values('108104','Settle Down - Single');
insert into `item` (`upc`, `title`) values('108413','The Veldt - EP');
insert into `item` (`upc`, `title`) values('108586','Discipline');
insert into `item` (`upc`, `title`) values('111519','In Light');
insert into `item` (`upc`, `title`) values('112478','Locked Out of Heaven - Single');
insert into `item` (`upc`, `title`) values('112735','Missundaztood');
insert into `item` (`upc`, `title`) values('113999','I Can\'t Stand Still');
insert into `item` (`upc`, `title`) values('115114','Evacuate the Dancefloor');
insert into `item` (`upc`, `title`) values('115186','Down To Earth');
insert into `item` (`upc`, `title`) values('115565','In Blue');
insert into `item` (`upc`, `title`) values('116761','Indie/Rock Playlist: October (2012)');
insert into `item` (`upc`, `title`) values('117517','Dying Is Your Latest Fashion');
insert into `item` (`upc`, `title`) values('117579','Stadium Arcadium');
insert into `item` (`upc`, `title`) values('117854','The Beatles (The White Album) (Remastered)');
insert into `item` (`upc`, `title`) values('119129','Big In Japan (feat. Idoling!!!) - Single');
insert into `item` (`upc`, `title`) values('119547','Me and My Gang');
insert into `item` (`upc`, `title`) values('120309','Let Me Clear My Throat');
insert into `item` (`upc`, `title`) values('120539','Riase!');
insert into `item` (`upc`, `title`) values('120830','Big Hoops (Bigger the Better) - Single');
insert into `item` (`upc`, `title`) values('123538','The Very Best of en Vogue');
insert into `item` (`upc`, `title`) values('123627','Only Girl (in the World)');
insert into `item` (`upc`, `title`) values('124597','I Love It (feat. Charli XCX) - Single');
insert into `item` (`upc`, `title`) values('124645','Yes');
insert into `item` (`upc`, `title`) values('125994','Guardians of the Galaxy: Awesome Mix, Vol. 1 (Original Motio');
insert into `item` (`upc`, `title`) values('126535','Pretty Vegas - Single');
insert into `item` (`upc`, `title`) values('127344','Are You Experienced');
insert into `item` (`upc`, `title`) values('127424','The Script');
insert into `item` (`upc`, `title`) values('127436','Pocket Full of Kryptonite');
insert into `item` (`upc`, `title`) values('127568','Masterpiece Theatre');
insert into `item` (`upc`, `title`) values('128264','Love\'s Not Dead - EP');
insert into `item` (`upc`, `title`) values('129428','Party Hard 2000');
insert into `item` (`upc`, `title`) values('129795','I Don\'t Care - Single');
insert into `item` (`upc`, `title`) values('130519','My Life Would Suck Without You - Single');
insert into `item` (`upc`, `title`) values('131011','hawaiii');
insert into `item` (`upc`, `title`) values('131090','Hey Now (feat. Kyle) - Single');
insert into `item` (`upc`, `title`) values('132525','Hypnotica');
insert into `item` (`upc`, `title`) values('132717','Handwritten (Deluxe)');
insert into `item` (`upc`, `title`) values('134622','Diamonds - Single');
insert into `item` (`upc`, `title`) values('134889','Dazed And Confused');
insert into `item` (`upc`, `title`) values('135479','Hard Candy');
insert into `item` (`upc`, `title`) values('135933','Bulletproof');
insert into `item` (`upc`, `title`) values('135948','Up All Night (Deluxe Version)');
insert into `item` (`upc`, `title`) values('136260','Feel the Love (Remixes) [feat. John Newman] - EP');
insert into `item` (`upc`, `title`) values('137102','Hallelujah - EP');
insert into `item` (`upc`, `title`) values('137433','Jackson 5: The Ultimate Collection');
insert into `item` (`upc`, `title`) values('137911','Unforgettable');
insert into `item` (`upc`, `title`) values('139479','Adventure');
insert into `item` (`upc`, `title`) values('139544','3 - Single');
insert into `item` (`upc`, `title`) values('140449','Part of Me - Single');
insert into `item` (`upc`, `title`) values('142857','Classified');
insert into `item` (`upc`, `title`) values('143072','Queen: Greatest Hits');
insert into `item` (`upc`, `title`) values('143624','Use Your Illusion I');
insert into `item` (`upc`, `title`) values('143877','Silence');
insert into `item` (`upc`, `title`) values('144470','No Air - Single');
insert into `item` (`upc`, `title`) values('145005','Merry Christmas');
insert into `item` (`upc`, `title`) values('145213','A Rush of Blood to the Head');
insert into `item` (`upc`, `title`) values('145428','Schizophonia');
insert into `item` (`upc`, `title`) values('145486','Sgt. Peppers Lonely Hearts Club Band (Remastered)');
insert into `item` (`upc`, `title`) values('148073','Get Lucky (Radio Edit) [feat. Pharrell Williams] - Single');
insert into `item` (`upc`, `title`) values('148917','Past Masters (Remastered)');
insert into `item` (`upc`, `title`) values('149344','Jagged Little Pill');
insert into `item` (`upc`, `title`) values('149946','Dizzy Up the Girl');
insert into `item` (`upc`, `title`) values('150264','Confessions Tour');
insert into `item` (`upc`, `title`) values('150509','Boyfriend - Single');
insert into `item` (`upc`, `title`) values('151832','Good Feeling - Single');
insert into `item` (`upc`, `title`) values('152209','Night Visions');
insert into `item` (`upc`, `title`) values('153804','Blink 182');
insert into `item` (`upc`, `title`) values('155616','I Want You - Single');
insert into `item` (`upc`, `title`) values('157314','Pearls of Passion');
insert into `item` (`upc`, `title`) values('157715','Greatest Hits - 1985-1995');
insert into `item` (`upc`, `title`) values('157800','Stripped');
insert into `item` (`upc`, `title`) values('159024','Grand');
insert into `item` (`upc`, `title`) values('160636','Best of Bowie');
insert into `item` (`upc`, `title`) values('161896','Have a Nice Day');
insert into `item` (`upc`, `title`) values('161940','Justified');
insert into `item` (`upc`, `title`) values('162807','Sean Kingston');
insert into `item` (`upc`, `title`) values('162884','Nevermind');
insert into `item` (`upc`, `title`) values('162973','Cross');
insert into `item` (`upc`, `title`) values('163759','Andrew McMahon In the Wilderness');
insert into `item` (`upc`, `title`) values('164516','The 50 Most Essential Pieces of Classical Music');
insert into `item` (`upc`, `title`) values('166061','I\'m Sorry...');
insert into `item` (`upc`, `title`) values('167028','Escape');
insert into `item` (`upc`, `title`) values('167594','We Found Love (feat. Calvin Harris) - Single');
insert into `item` (`upc`, `title`) values('168710','Time to Win, Vol. I');
insert into `item` (`upc`, `title`) values('170269','Infinity on High');
insert into `item` (`upc`, `title`) values('170675','Big Ones');
insert into `item` (`upc`, `title`) values('170947','Animals - Single');
insert into `item` (`upc`, `title`) values('171314','FOUR (Deluxe Version)');
insert into `item` (`upc`, `title`) values('172053','PRISM (Deluxe)');
insert into `item` (`upc`, `title`) values('172281','My Head Is an Animal');
insert into `item` (`upc`, `title`) values('172308','Club Life, Vol. Two: Miami');
insert into `item` (`upc`, `title`) values('172516','Rooty');
insert into `item` (`upc`, `title`) values('173191','Western Dream');
insert into `item` (`upc`, `title`) values('173739','How Do You Feel? - EP');
insert into `item` (`upc`, `title`) values('174198','Atlantis: Hymns for Disco');
insert into `item` (`upc`, `title`) values('174529','Wake Me Up - Single');
insert into `item` (`upc`, `title`) values('174693','One Life Stand (feat. Craig Smart)');
insert into `item` (`upc`, `title`) values('178062','Some Gave All');
insert into `item` (`upc`, `title`) values('178517','1000 Forms of Fear');
insert into `item` (`upc`, `title`) values('178887','Switch');
insert into `item` (`upc`, `title`) values('179466','The Annie Lennox Collection (Super Deluxe Version)');
insert into `item` (`upc`, `title`) values('179681','The Best Damn Thing');
insert into `item` (`upc`, `title`) values('179897','When the World Comes Down (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('181105','Sometimes');
insert into `item` (`upc`, `title`) values('181695','St. Elsewhere');
insert into `item` (`upc`, `title`) values('182043','All the Right Reasons');
insert into `item` (`upc`, `title`) values('183049','Europop');
insert into `item` (`upc`, `title`) values('183325','Stop! In the Name of Love / Free Your Mind (Glee Cast Versio');
insert into `item` (`upc`, `title`) values('183419','Never Trust a Happy Song');
insert into `item` (`upc`, `title`) values('183517','A Twist In My Story');
insert into `item` (`upc`, `title`) values('184406','Mylo Xyloto');
insert into `item` (`upc`, `title`) values('184556','Greatest Hits: My Prerogative');
insert into `item` (`upc`, `title`) values('185419','Cults');
insert into `item` (`upc`, `title`) values('186184','Crazy Hits');
insert into `item` (`upc`, `title`) values('186582','Body Diamond EP');
insert into `item` (`upc`, `title`) values('186963','Kala');
insert into `item` (`upc`, `title`) values('188183','The Love and Waffles Album');
insert into `item` (`upc`, `title`) values('188396','Born This Way - Single');
insert into `item` (`upc`, `title`) values('188561','Boom Boom Pow - Single');
insert into `item` (`upc`, `title`) values('189900','What\'s My Name? (feat. Drake) - Single');
insert into `item` (`upc`, `title`) values('190135','Barrio Fino (En Directo) [Bonus Track Version]');
insert into `item` (`upc`, `title`) values('190239','Barrio Fino en Directo');
insert into `item` (`upc`, `title`) values('190540','Exclusive');
insert into `item` (`upc`, `title`) values('190671','The Unplanned Mixtape');
insert into `item` (`upc`, `title`) values('190799','The Doors');
insert into `item` (`upc`, `title`) values('192066','If I Were a Boy/Single Ladies');
insert into `item` (`upc`, `title`) values('192502','Building the Perfect Beast');
insert into `item` (`upc`, `title`) values('193267','Random Access Memories');
insert into `item` (`upc`, `title`) values('193538','Crush');
insert into `item` (`upc`, `title`) values('194061','Funk Explosion');
insert into `item` (`upc`, `title`) values('194354','Womanizer - Single');
insert into `item` (`upc`, `title`) values('194358','Love Me Like You Do (From \"Fifty Shades of Grey\") - Single');
insert into `item` (`upc`, `title`) values('194739','Summer - Single');
insert into `item` (`upc`, `title`) values('196345','Uptown Funk (feat. Bruno Mars) - Single');
insert into `item` (`upc`, `title`) values('196432','The Fault In Our Stars (Music From the Motion Picture)');
insert into `item` (`upc`, `title`) values('197636','The Love Chronicles');
insert into `item` (`upc`, `title`) values('201163','Ice on the Dune');
insert into `item` (`upc`, `title`) values('203809','Hold It Against Me - Single');
insert into `item` (`upc`, `title`) values('204190','Give It 2 Me');
insert into `item` (`upc`, `title`) values('205084','Something Else');
insert into `item` (`upc`, `title`) values('205159','A Girl Like Me');
insert into `item` (`upc`, `title`) values('205510','Everytime We Touch - Single');
insert into `item` (`upc`, `title`) values('205822','Retrospective');
insert into `item` (`upc`, `title`) values('206112','Love. Angel. Music. Baby.');
insert into `item` (`upc`, `title`) values('206124','My Feelings For You');
insert into `item` (`upc`, `title`) values('208157','Yellow Submarine (Remastered)');
insert into `item` (`upc`, `title`) values('208614','Turn the Music Up - Single');
insert into `item` (`upc`, `title`) values('209388','Give Me the Music - Single');
insert into `item` (`upc`, `title`) values('209693','Fire Burning - Single');
insert into `item` (`upc`, `title`) values('210239','Help! (Remastered)');
insert into `item` (`upc`, `title`) values('211285','Ça m\'énerve - EP');
insert into `item` (`upc`, `title`) values('211645','Breath of Life - Single');
insert into `item` (`upc`, `title`) values('212054','All Possible Futures');
insert into `item` (`upc`, `title`) values('213265','Teenage Dream (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('213799','Ultra Dance 9');
insert into `item` (`upc`, `title`) values('214400','Human After All');
insert into `item` (`upc`, `title`) values('215805','The Ministry of Sound: Annual 2008');
insert into `item` (`upc`, `title`) values('215849','Country Girl (Shake It for Me) - Single');
insert into `item` (`upc`, `title`) values('216114','Nazareth - Greatest Hits');
insert into `item` (`upc`, `title`) values('216641','Masterpiece Theater');
insert into `item` (`upc`, `title`) values('217119','Skyfall - Single');
insert into `item` (`upc`, `title`) values('217403','Illumination');
insert into `item` (`upc`, `title`) values('219159','Sawdust');
insert into `item` (`upc`, `title`) values('219883','Dreaming Out Loud (Bonus Track Version)');
insert into `item` (`upc`, `title`) values('220249','As I Am');
insert into `item` (`upc`, `title`) values('220650','You\'re On (Remixes) [feat. Kyan] - Single');
insert into `item` (`upc`, `title`) values('221615','In the Zone');
insert into `item` (`upc`, `title`) values('222675','Thrift Shop (feat. Wanz) - Single');
insert into `item` (`upc`, `title`) values('223203','E=MC2');
insert into `item` (`upc`, `title`) values('223336','Continuum');
insert into `item` (`upc`, `title`) values('223546','3-Way (The Golden Rule) [feat. Justin Timberlake & Lady GaGa');
insert into `item` (`upc`, `title`) values('223943','The W.A.N.D. - Single');
insert into `item` (`upc`, `title`) values('224310','The Very Best... And Beyond');
insert into `item` (`upc`, `title`) values('224527','Meteora');
insert into `item` (`upc`, `title`) values('225037','Electroman (Deluxe Version)');
insert into `item` (`upc`, `title`) values('225330','A Drop In the Ocean - Single');
insert into `item` (`upc`, `title`) values('226240','Troubadour');
insert into `item` (`upc`, `title`) values('226328','Loose');
insert into `item` (`upc`, `title`) values('226395','Tonight: Franz Ferdinand');
insert into `item` (`upc`, `title`) values('227223','Lucky Shiner');
insert into `item` (`upc`, `title`) values('229189','Africa - Single');
insert into `item` (`upc`, `title`) values('229350','Need U (100%) [feat. A*M*E] [Remixes] ? EP');
insert into `item` (`upc`, `title`) values('229807','Push and Shove');
insert into `item` (`upc`, `title`) values('229990','Destination Calabria');
insert into `item` (`upc`, `title`) values('230090','Kick');
insert into `item` (`upc`, `title`) values('231141','Hideaway - EP');
insert into `item` (`upc`, `title`) values('232114','The Reminder');
insert into `item` (`upc`, `title`) values('233484','Scary Monsters and Nice Sprites');
insert into `item` (`upc`, `title`) values('234659','Greatest Hits');
insert into `item` (`upc`, `title`) values('235103','The Official Uk Top 40 Singles Chart 15-07-2012');
insert into `item` (`upc`, `title`) values('235370','Golden Classics');
insert into `item` (`upc`, `title`) values('236099','Just a Dream - Single');
insert into `item` (`upc`, `title`) values('236393','How To Save A Life');
insert into `item` (`upc`, `title`) values('238243','Middle of Nowhere');
insert into `item` (`upc`, `title`) values('238281','Orff: Carmina Burana');
insert into `item` (`upc`, `title`) values('238603','You Are Here - EP');
insert into `item` (`upc`, `title`) values('240692','Fefe Dobson');
insert into `item` (`upc`, `title`) values('241918','Party Rock Anthem (feat. Lauren Bennett & GoonRock) - Single');
insert into `item` (`upc`, `title`) values('242030','California Gurls');
insert into `item` (`upc`, `title`) values('242331','Revival');
insert into `item` (`upc`, `title`) values('243278','Frozen (Deluxe Edition) [Original Motion Picture Soundtrack]');
insert into `item` (`upc`, `title`) values('243949','Icarus - Single');
insert into `item` (`upc`, `title`) values('244110','Not Myself Tonight - Single');
insert into `item` (`upc`, `title`) values('245233','Definitely Maybe');
insert into `item` (`upc`, `title`) values('245425','I Am...Sasha Fierce');
insert into `item` (`upc`, `title`) values('245488','Talk That Talk (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('245647','Teenage Dream - Single');
insert into `item` (`upc`, `title`) values('245938','Mamma Mia!: The Movie Soundtrack');
insert into `item` (`upc`, `title`) values('246130','Pink Friday (Deluxe Version)');
insert into `item` (`upc`, `title`) values('246403','It\'s Madness Too');
insert into `item` (`upc`, `title`) values('247678','We the People');
insert into `item` (`upc`, `title`) values('247825','Speakerboxxx/ The Love Below');
insert into `item` (`upc`, `title`) values('248000','Shawn Mendes - EP');
insert into `item` (`upc`, `title`) values('249441','Coco');
insert into `item` (`upc`, `title`) values('249480','Chinese Democracy - Single');
insert into `item` (`upc`, `title`) values('249690','The Blueprint 3');
insert into `item` (`upc`, `title`) values('249797','PCD');
insert into `item` (`upc`, `title`) values('251669','Ultimate Santana');
insert into `item` (`upc`, `title`) values('252272','The Fray (Deluxe Version)');
insert into `item` (`upc`, `title`) values('252596','Gotta Be Somebody - Single');
insert into `item` (`upc`, `title`) values('252893','Top of the World (feat. Dev) - Single');
insert into `item` (`upc`, `title`) values('253914','Finale - Single');
insert into `item` (`upc`, `title`) values('253954','Now You\'re Gone');
insert into `item` (`upc`, `title`) values('254869','Music for the Motion Picture Into the Wild');
insert into `item` (`upc`, `title`) values('255418','Plastic Beach');
insert into `item` (`upc`, `title`) values('255627','Mash Up Mix 2007');
insert into `item` (`upc`, `title`) values('255736','Proper Education');
insert into `item` (`upc`, `title`) values('255994','Leap Year');
insert into `item` (`upc`, `title`) values('256119','I Ran: The Best of A Flock of Seagulls (Re-Recorded Versions');
insert into `item` (`upc`, `title`) values('257006','X&Y');
insert into `item` (`upc`, `title`) values('257315','Adventure Club Dubstep Remix');
insert into `item` (`upc`, `title`) values('258245','Combat Rock');
insert into `item` (`upc`, `title`) values('258282','Spirit');
insert into `item` (`upc`, `title`) values('259294','Doll Domination (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('259384','Rocket Man - Number Ones');
insert into `item` (`upc`, `title`) values('260192','I Like It (feat. Pitbull) - Single');
insert into `item` (`upc`, `title`) values('261246','Celebration (Deluxe Version)');
insert into `item` (`upc`, `title`) values('261531','I\'m Not Dead');
insert into `item` (`upc`, `title`) values('261598','Erase Me (feat. Kanye West) - Single');
insert into `item` (`upc`, `title`) values('262210','Violator');
insert into `item` (`upc`, `title`) values('264399','Where Them Girls At (feat. Nicki Minaj & Flo Rida) - Single');
insert into `item` (`upc`, `title`) values('264623','I Love You.');
insert into `item` (`upc`, `title`) values('265535','iTunes Festival - EP');
insert into `item` (`upc`, `title`) values('265598','Nothing But the Beat (Deluxe Version)');
insert into `item` (`upc`, `title`) values('265680','Classic Queen');
insert into `item` (`upc`, `title`) values('266175','Say It Right, Pt. 2');
insert into `item` (`upc`, `title`) values('267174','One Time - Single');
insert into `item` (`upc`, `title`) values('268844','The Madman\'s Return');
insert into `item` (`upc`, `title`) values('268850','White Women');
insert into `item` (`upc`, `title`) values('268935','The New Classic (Deluxe Version)');
insert into `item` (`upc`, `title`) values('269126','Jason Derulo');
insert into `item` (`upc`, `title`) values('270806','> album title goes here <');
insert into `item` (`upc`, `title`) values('271167','A Hard Day\'s Night (Remastered)');
insert into `item` (`upc`, `title`) values('272277','The Edge of Glory (The Remixes)');
insert into `item` (`upc`, `title`) values('272928','Number Ones');
insert into `item` (`upc`, `title`) values('273396','Daniel Powter');
insert into `item` (`upc`, `title`) values('274010','Beatles For Sale (Remastered)');
insert into `item` (`upc`, `title`) values('275410','Watermark');
insert into `item` (`upc`, `title`) values('276182','19');
insert into `item` (`upc`, `title`) values('277083','Rubber Soul (Remastered)');
insert into `item` (`upc`, `title`) values('277583','One of the Boys');
insert into `item` (`upc`, `title`) values('278032','Call Me Maybe - Single');
insert into `item` (`upc`, `title`) values('278393','Bad Romance - Single');
insert into `item` (`upc`, `title`) values('280118','Halcyon (Deluxe Version)');
insert into `item` (`upc`, `title`) values('280522','Remixed!');
insert into `item` (`upc`, `title`) values('281175','Breakout');
insert into `item` (`upc`, `title`) values('281450','Like Me / Stupid Shit 12\" Vinyl Single');
insert into `item` (`upc`, `title`) values('282898','Autobiography');
insert into `item` (`upc`, `title`) values('283716','The Age of Plastic');
insert into `item` (`upc`, `title`) values('283750','Warning');
insert into `item` (`upc`, `title`) values('285663','Physical Graffiti (Remastered)');
insert into `item` (`upc`, `title`) values('286682','Magic - Single');
insert into `item` (`upc`, `title`) values('287882','Ceremonials');
insert into `item` (`upc`, `title`) values('287954','Departure');
insert into `item` (`upc`, `title`) values('289465','Infinity - EP');
insert into `item` (`upc`, `title`) values('289839','Cross My Heart - Single');
insert into `item` (`upc`, `title`) values('291324','If I Were a Boy - Single');
insert into `item` (`upc`, `title`) values('291809','Teenage Dream: The Complete Confection');
insert into `item` (`upc`, `title`) values('293525','When The World Comes Down');
insert into `item` (`upc`, `title`) values('293776','Every Picture Tells a Story');
insert into `item` (`upc`, `title`) values('294539','Rockferry');
insert into `item` (`upc`, `title`) values('295714','The Chase Is On - Single');
insert into `item` (`upc`, `title`) values('295774','Doo-Wops & Hooligans (Deluxe Version)');
insert into `item` (`upc`, `title`) values('296222','Love at the End of the World');
insert into `item` (`upc`, `title`) values('296847','Blackout');
insert into `item` (`upc`, `title`) values('297005','Rise and Fall, Rage and Grace');
insert into `item` (`upc`, `title`) values('298027','Maybe You\'ve Been Brainwashed Too');
insert into `item` (`upc`, `title`) values('298664','Sigh No More');
insert into `item` (`upc`, `title`) values('300064','Quiet Riot - Greatest Hits');
insert into `item` (`upc`, `title`) values('300290','Backstreet\'s Back');
insert into `item` (`upc`, `title`) values('300740','Do What U Want (feat. Christina Aguilera) - Single');
insert into `item` (`upc`, `title`) values('301193','The Papercut Chronicles');
insert into `item` (`upc`, `title`) values('301374','Hysteria');
insert into `item` (`upc`, `title`) values('301957','TiK ToK - Single');
insert into `item` (`upc`, `title`) values('303872','Wish You Were Here (Deluxe Experience Version) [Remastered]');
insert into `item` (`upc`, `title`) values('304081','Happy - Single');
insert into `item` (`upc`, `title`) values('304169','Ministry of Sound - The Annual 2006 (Disc 2)');
insert into `item` (`upc`, `title`) values('304886','Celebration');
insert into `item` (`upc`, `title`) values('305527','B.o.B Presents: The Adventures of Bobby Ray (Deluxe)');
insert into `item` (`upc`, `title`) values('306250','Fire In Your New Shoes (feat. Dragonette) - Single');
insert into `item` (`upc`, `title`) values('307083','Days Go By - EP');
insert into `item` (`upc`, `title`) values('307105','Let It Be (Remastered)');
insert into `item` (`upc`, `title`) values('307221','As Cruel as School Children');
insert into `item` (`upc`, `title`) values('307378','The Kitsuné Special Edition #2 - Kitsuné Maison 12 + Gildas ');
insert into `item` (`upc`, `title`) values('307499','Mail On Sunday');
insert into `item` (`upc`, `title`) values('308133','Kindred');
insert into `item` (`upc`, `title`) values('308419','Tragic Kingdom');
insert into `item` (`upc`, `title`) values('308678','Rock This Party');
insert into `item` (`upc`, `title`) values('309265','Slipway Fires');
insert into `item` (`upc`, `title`) values('309474','The Inevitable And I');
insert into `item` (`upc`, `title`) values('309772','Hot Mess');
insert into `item` (`upc`, `title`) values('310319','Let It Rock - Single');
insert into `item` (`upc`, `title`) values('310728','PRISM (Deluxe Version)');
insert into `item` (`upc`, `title`) values('311961','Turn Your Back (With Anti-Flag) - Single');
insert into `item` (`upc`, `title`) values('313186','The Sweet Escape');
insert into `item` (`upc`, `title`) values('313640','Akimbo Alogo');
insert into `item` (`upc`, `title`) values('313989','I Just Had Sex - Single');
insert into `item` (`upc`, `title`) values('314416','Ultra Mix');
insert into `item` (`upc`, `title`) values('315438','Konvicted');
insert into `item` (`upc`, `title`) values('315766','After the Snow');
insert into `item` (`upc`, `title`) values('317109','Golden - Single');
insert into `item` (`upc`, `title`) values('317730','Minutes to Midnight');
insert into `item` (`upc`, `title`) values('319330','Wild Life (Deluxe Version)');
insert into `item` (`upc`, `title`) values('319522','Night Is Young - Single');
insert into `item` (`upc`, `title`) values('320169','E.T. (feat. Kanye West) - Single');
insert into `item` (`upc`, `title`) values('320421','Midnight Memories (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('320861','Merriweather Post Pavilion');
insert into `item` (`upc`, `title`) values('321656','Lungs');
insert into `item` (`upc`, `title`) values('323075','Monkey Business');
insert into `item` (`upc`, `title`) values('323088','Rebel Heart');
insert into `item` (`upc`, `title`) values('324479','MDNA (Deluxe Version)');
insert into `item` (`upc`, `title`) values('325629','A Little Bit of Mambo');
insert into `item` (`upc`, `title`) values('325826','Manners');
insert into `item` (`upc`, `title`) values('326873','Tidings: 6 Songs for the Season');
insert into `item` (`upc`, `title`) values('327189','Same Love (feat. Mary Lambert) - Single');
insert into `item` (`upc`, `title`) values('327201','Stolen Dance - EP');
insert into `item` (`upc`, `title`) values('327457','Tha Smokin\' Nephew');
insert into `item` (`upc`, `title`) values('327897','Hey Ya!');
insert into `item` (`upc`, `title`) values('328194','Is It O.K.');
insert into `item` (`upc`, `title`) values('328701','Confessions on a Dance Floor');
insert into `item` (`upc`, `title`) values('328973','Martell - EP');
insert into `item` (`upc`, `title`) values('329278','Them VS. You VS. Me');
insert into `item` (`upc`, `title`) values('330959','Passive Me, Aggressive You');
insert into `item` (`upc`, `title`) values('331065','Mr. Bad Guy');
insert into `item` (`upc`, `title`) values('331785','Give Me Everything (feat. Ne-Yo, Afrojack & Nayer) - Single');
insert into `item` (`upc`, `title`) values('332121','Millennium');
insert into `item` (`upc`, `title`) values('332180','With The Beatles (Remastered)');
insert into `item` (`upc`, `title`) values('332325','Know Your Enemy - Single');
insert into `item` (`upc`, `title`) values('332360','Crayons');
insert into `item` (`upc`, `title`) values('333352','Moves Like Jagger (The Voice Performance) [feat. Christina A');
insert into `item` (`upc`, `title`) values('334820','Revolver (Remixes)');
insert into `item` (`upc`, `title`) values('335264','Funhouse');
insert into `item` (`upc`, `title`) values('335389','I Kissed A Girl - Single');
insert into `item` (`upc`, `title`) values('335631','Edward Sharpe & The Magnetic Zeros');
insert into `item` (`upc`, `title`) values('337937','MTV Ultimate Mash-Ups Presents: Collision Course - Numb / En');
insert into `item` (`upc`, `title`) values('338582','Feel EP');
insert into `item` (`upc`, `title`) values('339235','Brave');
insert into `item` (`upc`, `title`) values('340208','R.O.O.T.S.');
insert into `item` (`upc`, `title`) values('340353','Jordin Sparks');
insert into `item` (`upc`, `title`) values('340415','Money Sucks, Friends Rule');
insert into `item` (`upc`, `title`) values('341062','Circus');
insert into `item` (`upc`, `title`) values('341637','Motion');
insert into `item` (`upc`, `title`) values('341756','Burnin\' Up - Single ');
insert into `item` (`upc`, `title`) values('342896','Settle');
insert into `item` (`upc`, `title`) values('342946','Tonight (I\'m Lovin\' You) [feat. Ludacris & DJ Frank E] - Sin');
insert into `item` (`upc`, `title`) values('343272','Journey: Greatest Hits');
insert into `item` (`upc`, `title`) values('343302','Ramones');
insert into `item` (`upc`, `title`) values('343454','#SELFIE - Single');
insert into `item` (`upc`, `title`) values('343663','Ministry of Sound - Ibiza Annual [Disc 1]');
insert into `item` (`upc`, `title`) values('343794','It Won\'t Be Soon Before Long');
insert into `item` (`upc`, `title`) values('343799','I Wanna Get Better - Single');
insert into `item` (`upc`, `title`) values('345500','Platinum & Gold Collection: Real McCoy');
insert into `item` (`upc`, `title`) values('346677','Appetite for Destruction');
insert into `item` (`upc`, `title`) values('346825','Back to Basics');
insert into `item` (`upc`, `title`) values('347222','Zombies! Aliens! Vampires! Dinosaurs!');
insert into `item` (`upc`, `title`) values('348505','The Greatest Hits');
insert into `item` (`upc`, `title`) values('352128','Whatever People Say I Am Thats What I Am Not');
insert into `item` (`upc`, `title`) values('353553','Chemical City (Dig)');
insert into `item` (`upc`, `title`) values('354896','All Around the World (feat. Ludacris) - Single');
insert into `item` (`upc`, `title`) values('354918','Crew Cuts');
insert into `item` (`upc`, `title`) values('355222','PSY 6_ (Six Rules), Pt. 1 - EP');
insert into `item` (`upc`, `title`) values('357741','Nena');
insert into `item` (`upc`, `title`) values('358320','Fantasy Ride');
insert into `item` (`upc`, `title`) values('358493','Back to Black');
insert into `item` (`upc`, `title`) values('359246','Eat Sleep Rave Repeat (feat. Beardyman) [Calvin Harris Remix');
insert into `item` (`upc`, `title`) values('360213','Crack a Bottle - Single');
insert into `item` (`upc`, `title`) values('360674','Megalithic Symphony');
insert into `item` (`upc`, `title`) values('361950','While the City Sleeps, We Rule the Streets');
insert into `item` (`upc`, `title`) values('362808','The Heist (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('362897','Rock N Roll Jesus');
insert into `item` (`upc`, `title`) values('363556','Just the Way You Are - Single');
insert into `item` (`upc`, `title`) values('363723','Layla and Other Assorted Love Songs');
insert into `item` (`upc`, `title`) values('364151','The Best Of');
insert into `item` (`upc`, `title`) values('364398','Till the World Ends - Single');
insert into `item` (`upc`, `title`) values('364635','Welcome Interstate Managers');
insert into `item` (`upc`, `title`) values('364869','Greatest Hits...So Far!!!');
insert into `item` (`upc`, `title`) values('364916','Breakout Platinum Edition');
insert into `item` (`upc`, `title`) values('365173','(What\'s the Story) Morning Glory');
insert into `item` (`upc`, `title`) values('365435','Strange Desire');
insert into `item` (`upc`, `title`) values('365560','London Calling');
insert into `item` (`upc`, `title`) values('367364','Hot Fuss');
insert into `item` (`upc`, `title`) values('369592','Red Light District - EP');
insert into `item` (`upc`, `title`) values('369936','111 Chopin Masterpieces');
insert into `item` (`upc`, `title`) values('370375','Something to Be');
insert into `item` (`upc`, `title`) values('370826','Run the World (Girls) - Single');
insert into `item` (`upc`, `title`) values('371994','Hold On, We\'re Going Home (feat. Majid Jordan) - Single');
insert into `item` (`upc`, `title`) values('372068','Forever');
insert into `item` (`upc`, `title`) values('372161','Homework');
insert into `item` (`upc`, `title`) values('373075','Ocean Eyes');
insert into `item` (`upc`, `title`) values('373383','Die In Your Arms - Single');
insert into `item` (`upc`, `title`) values('374146','High Strung');
insert into `item` (`upc`, `title`) values('376084','Shake It Out (Remixes) - EP');
insert into `item` (`upc`, `title`) values('376814','Turn to You (Mother\'s Day Dedication) - Single');
insert into `item` (`upc`, `title`) values('377326','Todos Los Exitos De La Rana Loca');
insert into `item` (`upc`, `title`) values('377866','The Lateness Of The Hour');
insert into `item` (`upc`, `title`) values('378059','Very Good Bad Thing (Deluxe Version)');
insert into `item` (`upc`, `title`) values('378060','Native (Deluxe Version)');
insert into `item` (`upc`, `title`) values('378259','On the Floor (feat. Pitbull) - Single');
insert into `item` (`upc`, `title`) values('379617','The Veldt (feat. Chris James) - Single');
insert into `item` (`upc`, `title`) values('379709','Exitos de Gloria Estefan');
insert into `item` (`upc`, `title`) values('379825','Listen to Your Heart');
insert into `item` (`upc`, `title`) values('379864','21st Century Breakdown');
insert into `item` (`upc`, `title`) values('379942','Elevate - Single');
insert into `item` (`upc`, `title`) values('382233','Sorry for Party Rocking (Deluxe Version)');
insert into `item` (`upc`, `title`) values('382741','Home (Deluxe Edition)');
insert into `item` (`upc`, `title`) values('384937','Slumdog Millionaire');
insert into `item` (`upc`, `title`) values('385215','Sex & Violins');
insert into `item` (`upc`, `title`) values('385544','Hozier');
insert into `item` (`upc`, `title`) values('385565','Wolfgang Amadeus');
insert into `item` (`upc`, `title`) values('385839','Final Countdown');
insert into `item` (`upc`, `title`) values('385931','Electric Feel (Justice Remix) - Single');
insert into `item` (`upc`, `title`) values('386749','Almost Alice (Music Inspired By the Motion Picture)');
insert into `item` (`upc`, `title`) values('386953','MoM & DaD');
insert into `item` (`upc`, `title`) values('387558','Let Me Think About It (Remixes) - EP');
insert into `item` (`upc`, `title`) values('387595','Ultimate: Prince');
insert into `item` (`upc`, `title`) values('388409','David Cook');
insert into `item` (`upc`, `title`) values('388970','One Heart');
insert into `item` (`upc`, `title`) values('389044','Imagine');
insert into `item` (`upc`, `title`) values('389715','Chill Em All');
insert into `item` (`upc`, `title`) values('390318','Don\'t Kill the Magic');
insert into `item` (`upc`, `title`) values('390529','Timebomb - Single');
insert into `item` (`upc`, `title`) values('391895','Fiona Coyne / Fall Harder - Single');
insert into `item` (`upc`, `title`) values('392116','Storyteller');
insert into `item` (`upc`, `title`) values('393676','Smiley Smile');
insert into `item` (`upc`, `title`) values('393952','Project X (Original Motion Picture Soundtrack) [Deluxe Editi');
insert into `item` (`upc`, `title`) values('394017','Yeah 3X - Single');
insert into `item` (`upc`, `title`) values('394511','I Wish (Live from Stevie Wonder\'s Tribute Concert) - Single');
insert into `item` (`upc`, `title`) values('395721','Eyes Open');
insert into `item` (`upc`, `title`) values('396538','The Spirit Indestructible (Deluxe Version)');
insert into `item` (`upc`, `title`) values('397054','Americana');
insert into `item` (`upc`, `title`) values('398222','Some Nights');
insert into `item` (`upc`, `title`) values('399957','Aphrodite');
insert into `item` (`upc`, `title`) values('400212','Colours');
insert into `item` (`upc`, `title`) values('400925','The Fame Monster');
insert into `item` (`upc`, `title`) values('400963','Walking On A Dream (Deluxe)');
insert into `item` (`upc`, `title`) values('401707','Given To The Wild');
insert into `item` (`upc`, `title`) values('402493','Falco 3');
insert into `item` (`upc`, `title`) values('402502','Promiscuous - Single');
insert into `item` (`upc`, `title`) values('403272','Watch Out - Single');
insert into `item` (`upc`, `title`) values('403916','Pop Life');
insert into `item` (`upc`, `title`) values('405199','Streets Advocate');
insert into `item` (`upc`, `title`) values('405249','Machine Head');
insert into `item` (`upc`, `title`) values('406101','Pieces of You');
insert into `item` (`upc`, `title`) values('407039','Just Say Yes - Single');
insert into `item` (`upc`, `title`) values('408451','Angel - Single');
insert into `item` (`upc`, `title`) values('409783','The Works');
insert into `item` (`upc`, `title`) values('410282','Graduation');
insert into `item` (`upc`, `title`) values('414400','Days Are Gone');
insert into `item` (`upc`, `title`) values('416902','Hurry Up, We\'re Dreaming.');
insert into `item` (`upc`, `title`) values('416919','Hips Don\'t Lie');
insert into `item` (`upc`, `title`) values('417911','Brett');
insert into `item` (`upc`, `title`) values('418681','Sam Sparro');
insert into `item` (`upc`, `title`) values('420238','Bionic (Deluxe Version)');
insert into `item` (`upc`, `title`) values('421077','Love');
insert into `item` (`upc`, `title`) values('422318','Whoa, Nelly!');
insert into `item` (`upc`, `title`) values('423201','Good Girl Gone Bad');
insert into `item` (`upc`, `title`) values('424740','The 2nd Law (Deluxe Version)');
insert into `item` (`upc`, `title`) values('425555','Not 4 Sale');
insert into `item` (`upc`, `title`) values('425681','Levels - Single');
insert into `item` (`upc`, `title`) values('425956','Hold On Now, Youngster...');
insert into `item` (`upc`, `title`) values('426309','FutureSex/LoveSounds');
insert into `item` (`upc`, `title`) values('427352','Magical Mystery Tour (Remastered)');
insert into `item` (`upc`, `title`) values('427521','Songs for You, Truths for Me');
insert into `item` (`upc`, `title`) values('427523','Billboard Top Dance Hits: 1978');
insert into `item` (`upc`, `title`) values('429168','Blur');
insert into `item` (`upc`, `title`) values('429952','Thank You Happy Birthday');
insert into `item` (`upc`, `title`) values('430388','Thank You, - Single');
insert into `item` (`upc`, `title`) values('431238','Without You (feat. Totally Enormous Extinct Dinosaurs) - Sin');
insert into `item` (`upc`, `title`) values('431781','Take Care (Deluxe Version)');
insert into `item` (`upc`, `title`) values('432533','Gipsy Kings');
insert into `item` (`upc`, `title`) values('432576','Nothing But the Beat');
insert into `item` (`upc`, `title`) values('433723','Call On Me - Single');
insert into `item` (`upc`, `title`) values('433786','Big Shiny Tunes');
insert into `item` (`upc`, `title`) values('433965','Surfacing');
insert into `item` (`upc`, `title`) values('434447','blink-182');
insert into `item` (`upc`, `title`) values('435118','Parallel Play - EP');
insert into `item` (`upc`, `title`) values('435724','Foreigner');
insert into `item` (`upc`, `title`) values('437217','Turn the Music Up');
insert into `item` (`upc`, `title`) values('437499','Discovery');
insert into `item` (`upc`, `title`) values('437665','So What - Single');
insert into `item` (`upc`, `title`) values('438089','Oh, What a Life');
insert into `item` (`upc`, `title`) values('438112','Teenage Dream - The Complete Confection');
insert into `item` (`upc`, `title`) values('439222','Waking Up (Deluxe Version)');
insert into `item` (`upc`, `title`) values('439444','Does You Inspire You');
insert into `item` (`upc`, `title`) values('440161','Gorillaz');
insert into `item` (`upc`, `title`) values('443126','Be Impressive');
insert into `item` (`upc`, `title`) values('443238','Burgz - Single');
insert into `item` (`upc`, `title`) values('443258','Paris');
insert into `item` (`upc`, `title`) values('443672','Lunatic');
insert into `item` (`upc`, `title`) values('444132','Runnin (feat. Dru & Lincoln)');
insert into `item` (`upc`, `title`) values('444339','Falling Down - Single');
insert into `item` (`upc`, `title`) values('445976','Viva la Vida or Death and All His Friends');
insert into `item` (`upc`, `title`) values('446028','Exposed');
insert into `item` (`upc`, `title`) values('446206','Whatcha Say - Single');
insert into `item` (`upc`, `title`) values('447407','Cross Road');
insert into `item` (`upc`, `title`) values('449284','Smoke + Mirrors (Deluxe)');
insert into `item` (`upc`, `title`) values('449841','Make It Home (feat. Kina Grannis) - Single');
insert into `item` (`upc`, `title`) values('450590','Kinks');
insert into `item` (`upc`, `title`) values('451360','Famous Last Words');
insert into `item` (`upc`, `title`) values('451386','Shine');
insert into `item` (`upc`, `title`) values('452261','Bunkka');
insert into `item` (`upc`, `title`) values('452485','Classical Chillout');
insert into `item` (`upc`, `title`) values('455330','Summit Sanctuary');
insert into `item` (`upc`, `title`) values('457901','Finger Eleven');
insert into `item` (`upc`, `title`) values('458782','Ray of Light');
insert into `item` (`upc`, `title`) values('458831','Reckless');
insert into `item` (`upc`, `title`) values('459481','Easy A (Original Motion Picture Soundtrack)');
insert into `item` (`upc`, `title`) values('459676','Teenage Dream (Glee Cast Version) - Single');
insert into `item` (`upc`, `title`) values('459804','The Sign');
insert into `item` (`upc`, `title`) values('461002','ARTPOP');
insert into `item` (`upc`, `title`) values('461163','Give Me the Music');
insert into `item` (`upc`, `title`) values('461694','Bandits (Music from the Motion Picture)');
insert into `item` (`upc`, `title`) values('462191','Like A Prayer');
insert into `item` (`upc`, `title`) values('462776','The Time (Dirty Bit) - Single');
insert into `item` (`upc`, `title`) values('463422','Queen: Absolute Greatest (2009 Remastered)');
insert into `item` (`upc`, `title`) values('465036','Year of the Gentleman');
insert into `item` (`upc`, `title`) values('465758','Piano Man');
insert into `item` (`upc`, `title`) values('467163','Flo Rida (feat. Ke$ha) - Single');
insert into `item` (`upc`, `title`) values('467410','Golden - EP');
insert into `item` (`upc`, `title`) values('468440','Fire');
insert into `item` (`upc`, `title`) values('469194','Harlem Shake - Single');
insert into `item` (`upc`, `title`) values('469250','A Hundred Million Suns');
insert into `item` (`upc`, `title`) values('470390','Paradise');
insert into `item` (`upc`, `title`) values('470494','Party Rock');
insert into `item` (`upc`, `title`) values('473033','Summertime Sadness (Lana Del Rey vs. Cedric Gervais) [Cedric');
insert into `item` (`upc`, `title`) values('473581','One Night Only');
insert into `item` (`upc`, `title`) values('473831','Rocket Man: Number Ones');
insert into `item` (`upc`, `title`) values('473911','Blurred Lines (feat. T.I. & Pharrell) - Single');
insert into `item` (`upc`, `title`) values('474055','Magna Carta... Holy Grail');
insert into `item` (`upc`, `title`) values('474219','Alice In Wonderland');
insert into `item` (`upc`, `title`) values('474537','How Big, How Blue, How Beautiful (Deluxe)');
insert into `item` (`upc`, `title`) values('476094','Barbra Streisand - Single');
insert into `item` (`upc`, `title`) values('476569','U Smile - Single');
insert into `item` (`upc`, `title`) values('477292','If You\'re Reading This It\'s Too Late');
insert into `item` (`upc`, `title`) values('478374','Folklore');
insert into `item` (`upc`, `title`) values('478491','Madman Across the Water');
insert into `item` (`upc`, `title`) values('479231','Grosse Pointe Blank: Music From The Film');
insert into `item` (`upc`, `title`) values('480871','Born This Way (Bonus Track Version)');
insert into `item` (`upc`, `title`) values('481673','In the City (Bonus Track Version)');
insert into `item` (`upc`, `title`) values('481694','Fixin\' to Thrill');
insert into `item` (`upc`, `title`) values('481905','Forever - Single');
insert into `item` (`upc`, `title`) values('482150','Light Me Up');
insert into `item` (`upc`, `title`) values('482252','Last Train to Paris (Deluxe Version)');
insert into `item` (`upc`, `title`) values('482486','For Your Entertainment');
insert into `item` (`upc`, `title`) values('482761','Every Teardrop Is a Waterfall - Single');
insert into `item` (`upc`, `title`) values('482952','Feel So Close');
insert into `item` (`upc`, `title`) values('483171','F**k You - Single');
insert into `item` (`upc`, `title`) values('483191','Tug Of War');
insert into `item` (`upc`, `title`) values('483876','Now Latino, Vol. 2');
insert into `item` (`upc`, `title`) values('484136','My Songs Know What You Did In the Dark (Light Em Up) - Singl');
insert into `item` (`upc`, `title`) values('484571','Summer Girl - Single');
insert into `item` (`upc`, `title`) values('485227','Move Along');
insert into `item` (`upc`, `title`) values('486569','Leave This Town');
insert into `item` (`upc`, `title`) values('487055','Dirty Dancer (with Usher) [feat. Lil Wayne] - Single');
insert into `item` (`upc`, `title`) values('488258','Tsunami - Single');
insert into `item` (`upc`, `title`) values('488328','Franz Ferdinand');
insert into `item` (`upc`, `title`) values('489031','One Love');
insert into `item` (`upc`, `title`) values('490053','Nimrod');
insert into `item` (`upc`, `title`) values('491159','Unwritten');
insert into `item` (`upc`, `title`) values('492093','Seal');
insert into `item` (`upc`, `title`) values('492200','You Are Not A Robot - Single');
insert into `item` (`upc`, `title`) values('493390','Weekends!!! (feat. Sirah) - Single');
insert into `item` (`upc`, `title`) values('495125','Checks Thugs & Rock N Roll');
insert into `item` (`upc`, `title`) values('495465','Holly');
insert into `item` (`upc`, `title`) values('495623','The Secret Life of Walter Mitty (Music From and Inspired By ');
insert into `item` (`upc`, `title`) values('496060','The Razor\'s Edge');
insert into `item` (`upc`, `title`) values('496464','The Guest');
insert into `item` (`upc`, `title`) values('496610','Dog Days Are Over (Glee Cast Version) - Single');
insert into `item` (`upc`, `title`) values('496931','Highway 61 Revisited');
insert into `item` (`upc`, `title`) values('496967','Airplanes (feat. Hayley Williams of Paramore) - Single');
insert into `item` (`upc`, `title`) values('497171','Oracular Spectacular');
insert into `item` (`upc`, `title`) values('499028','Sam\'s Town');
insert into `item` (`upc`, `title`) values('499044','The Edge of Glory - Single');
insert into `item` (`upc`, `title`) values('499421','Control - Single');
insert into `item` (`upc`, `title`) values('499846','A Very Gaga Holiday (Live) - EP');
insert into `item` (`upc`, `title`) values('500397','I Got U (feat. Jax Jones) - Single');
insert into `item` (`upc`, `title`) values('500946','Street Gospels');
insert into `item` (`upc`, `title`) values('501636','Only By The Night');
insert into `item` (`upc`, `title`) values('502077','Highway to Hell');
insert into `item` (`upc`, `title`) values('502387','The Time of Our Lives');
insert into `item` (`upc`, `title`) values('503484','Tribute (Deluxe Version)');
insert into `item` (`upc`, `title`) values('504362','She Wolf - Single');
insert into `item` (`upc`, `title`) values('505117','Take a Bow - Single');
insert into `item` (`upc`, `title`) values('507242','People Keep Talking');
insert into `item` (`upc`, `title`) values('507296','Live My Life (feat. Justin Bieber) - Single');
insert into `item` (`upc`, `title`) values('508821','Please Please Me (Remastered)');
insert into `item` (`upc`, `title`) values('509635','Push and Shove (feat. Busy Signal, Major Lazer) - Single');
insert into `item` (`upc`, `title`) values('509884','The Best of Poison - 20 Years of Rock');
insert into `item` (`upc`, `title`) values('510278','Keeps Gettin\' Better - Single');
insert into `item` (`upc`, `title`) values('510578','Thriller');
insert into `item` (`upc`, `title`) values('511060','Clapton Chronicles - The Best of Eric Clapton');
insert into `item` (`upc`, `title`) values('512880','Born to Die (Deluxe Version)');
insert into `item` (`upc`, `title`) values('514079','El Camino');
insert into `item` (`upc`, `title`) values('514454','Pocketful of Sunshine');
insert into `item` (`upc`, `title`) values('514572','The Great Gatsby (Music from Baz Luhrmann\'s Film) [Deluxe Ed');
insert into `item` (`upc`, `title`) values('515166','Chariot');
insert into `item` (`upc`, `title`) values('515935','The Brooklyn (Extended Play)');
insert into `item` (`upc`, `title`) values('516520','The Boy Who Knew Too Much');
insert into `item` (`upc`, `title`) values('516847','Femme Fatale');
insert into `item` (`upc`, `title`) values('518274','Recovery');
insert into `item` (`upc`, `title`) values('518404','Exile on Mainstream');
insert into `item` (`upc`, `title`) values('518917','The Lumineers');
insert into `item` (`upc`, `title`) values('519181','Start Me Up / Livin\' On a Prayer (Glee Cast Version) - Singl');
insert into `item` (`upc`, `title`) values('519260','15');
insert into `item` (`upc`, `title`) values('519307','She\'s So Unusual');
insert into `item` (`upc`, `title`) values('520137','Doll Domination');
insert into `item` (`upc`, `title`) values('520371','Actually');
insert into `item` (`upc`, `title`) values('523059','From Under the Cork Tree');
insert into `item` (`upc`, `title`) values('523219','Gossamer');
insert into `item` (`upc`, `title`) values('524155','Slumdog Millionaire (Music from the Motion Picture)');
insert into `item` (`upc`, `title`) values('524540','Saving Abel');
insert into `item` (`upc`, `title`) values('525924','Hungry Ghosts');
insert into `item` (`upc`, `title`) values('525945','Led Zeppelin IV');
insert into `item` (`upc`, `title`) values('526516','Galore');
insert into `item` (`upc`, `title`) values('527290','Little Voice');
insert into `item` (`upc`, `title`) values('527709','Insomniac');
insert into `item` (`upc`, `title`) values('527834','Cinema (Remixes) [feat. Gary Go], Pt. 2 - EP');
insert into `item` (`upc`, `title`) values('529547','The Night Out');
insert into `item` (`upc`, `title`) values('530194','Music of the Sun');
insert into `item` (`upc`, `title`) values('530960','I Will Wait - Single');
insert into `item` (`upc`, `title`) values('532150','Cha-Ching - Single');
insert into `item` (`upc`, `title`) values('533421','The Silver Collection');
insert into `item` (`upc`, `title`) values('533835','I Ran: The Best Of');
insert into `item` (`upc`, `title`) values('534819','Led Zeppelin III');
insert into `item` (`upc`, `title`) values('536429','Blurred Lines (Deluxe Version)');
insert into `item` (`upc`, `title`) values('537878','Enema Of The State');
insert into `item` (`upc`, `title`) values('538528','Sweet Nothing (feat. Florence Welch) - Single');
insert into `item` (`upc`, `title`) values('538578','St. Lucia - EP');
insert into `item` (`upc`, `title`) values('538608','Sweet Dreams (Are Made of This)');
insert into `item` (`upc`, `title`) values('538611','Animal');
insert into `item` (`upc`, `title`) values('538878','High Noon');
insert into `item` (`upc`, `title`) values('539372','Fijacion Oral vol. 1');
insert into `item` (`upc`, `title`) values('540205','A Fever You Can\'t Sweat Out');
insert into `item` (`upc`, `title`) values('540237','Pop Psychology');
insert into `item` (`upc`, `title`) values('540389','At War With the Mystics');
insert into `item` (`upc`, `title`) values('541677','More Beautiful Than Silence - EP');
insert into `item` (`upc`, `title`) values('542139','Cha Cha Slide');
insert into `item` (`upc`, `title`) values('542723','Cooler Than Me - Single');
insert into `item` (`upc`, `title`) values('543508','AM');
insert into `item` (`upc`, `title`) values('543939','The Great Gatsby (Music From Baz Luhrmann\'s Film)');
insert into `item` (`upc`, `title`) values('544342','Ultimate Christmas Collection');
insert into `item` (`upc`, `title`) values('123456789','RYAN TEST');
